### Default config
# Used to setup general parameters for the simulator

robot:
  radius: 12.5
  max_v: 2
  camera_sensor_range: 40
  print_bt: False

warehouse:
  box_radius: 12.5
  width: 500
  height: 500
  repulsion_wall: 25
  repulsion_object: 25
  object_position: 2
  exit_width: 25

faults: []

time_limit: 30000 
animate: True
save_animation: False
heading_bias: False
box_attraction: False
heading_change_rate: 100 # ticks per change in heading
capture_data: False

