### Default config
# Used to setup general parameters for the simulator

robot:
  radius: 12.5
  max_v: 2
  camera_sensor_range: 100 # cm
  communication_range: 500 # cm
  print_bt: False

print_kg: False

warehouse:
  box_radius: 12.5
  width: 2500
  height: 2500
  repulsion_wall: 25
  repulsion_object: 25
  exit_width: 25

faults: []

time_limit: 50000
animate: True
save_animation: False
heading_change_rate: 100 # ticks per change in heading
capture_data: False

