### Default config
# Used to setup general parameters for the simulator

robot:
  radius: 12.5
  max_v: 2
  camera_sensor_range: 100
  print_bt: False

warehouse:
  box_radius: 12.5
  width: 1000
  height: 1000
  repulsion_wall: 20
  repulsion_object: 20
  exit_width: 25

faults: []

time_limit: 5000 
animate: True
save_animation: False
heading_bias: False
box_attraction: False
heading_change_rate: 100 # ticks per change in heading
capture_data: False

