image: python:3.9

pipelines:
  branches:
    hm_v2_testing:
      - step:
          name: Build and Deploy MkDocs
          caches:
            - pip
          script:
            - pip install mkdocs mkdocs-material
            - mkdocs build
            - mkdir -p public
            - cp -r site/* public/
          artifacts:
            - public/**
      - step:
          name: Deploy to Bitbucket Pages
          deployment: production
          script:
            - pipe: atlassian/bitbucket-pipe-deploy-static-site:1.0.0
              variables:
                STATIC_SITE_PATH: "public"
                CONTENT_SERVING: "static-site"
