site_name: Hive v2 Documentation
theme:
  name: material

nav:
  - Home: index.md
  - API Reference:
      - Simulator: sim.md
      - Visualiser: viz_sim.md
      - Warehouse: warehouse.md
      - Objects: objects.md
      - Hive: hive_mind.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["../simulator"]

